services:
  server:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app

  db:
    image: "postgres:latest"
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PORT=${DB_PORT}
    ports:
      - "5434:5432"
    volumes:
      - database-data:/var/lib/postgresql/data

volumes:
  database-data: